# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title title
#'
#' @description
#' description
#'
#'
#' @param x x
#'
#' @details
#'
#' details
#'
#' @return a vector
#'
#'
#' @author Raphaël Jauslin \email{raphael.jauslin@@unine.ch}
#'
#' @seealso
#' func
#'
#' @examples
#'
#' @export
parma <- function(X, pik, nthreads, EPS = 0.0000001) {
    .Call(`_tinyFF_parma`, X, pik, nthreads, EPS)
}

#' @title title
#'
#' @description
#' description
#'
#'
#' @param x x
#'
#' @details
#'
#' details
#'
#' @return a vector
#'
#'
#' @author Raphaël Jauslin \email{raphael.jauslin@@unine.ch}
#'
#' @seealso
#' func
#'
#' @examples
#'
#' @export
cube <- function(prob, Xbal) {
    .Call(`_tinyFF_cube`, prob, Xbal)
}

#' @title title
#'
#' @description
#' description
#'
#'
#' @param x x
#'
#' @details
#'
#' details
#'
#' @return a vector
#'
#'
#' @author Raphaël Jauslin \email{raphael.jauslin@@unine.ch}
#'
#' @seealso
#' func
#'
#' @examples
#'
#' @export
lcube <- function(prob, Xspread, Xbal) {
    .Call(`_tinyFF_lcube`, prob, Xspread, Xbal)
}

#' @title title
#'
#' @description
#' description
#'
#'
#' @param x x
#'
#' @details
#'
#' details
#'
#' @return a vector
#'
#'
#' @author Raphaël Jauslin \email{raphael.jauslin@@unine.ch}
#'
#' @seealso
#' func
#'
#' @examples
#'
#' @export
flightphase <- function(prob, Xbal) {
    .Call(`_tinyFF_flightphase`, prob, Xbal)
}

#' @title title
#'
#' @description
#' description
#'
#'
#' @param x x
#'
#' @details
#'
#' details
#'
#' @return a vector
#'
#'
#' @author Raphaël Jauslin \email{raphael.jauslin@@unine.ch}
#'
#' @seealso
#' func
#'
#' @examples
#'
#' @export
landingphase <- function(prob, probflight, Xbal) {
    .Call(`_tinyFF_landingphase`, prob, probflight, Xbal)
}

#' @title title
#'
#' @description
#' description
#'
#'
#' @param x x
#'
#' @details
#'
#' details
#'
#' @return a vector
#'
#'
#' @author Raphaël Jauslin \email{raphael.jauslin@@unine.ch}
#'
#' @seealso
#' func
#'
#' @examples
#'
#' @export
lcubeflightphase <- function(prob, Xspread, Xbal) {
    .Call(`_tinyFF_lcubeflightphase`, prob, Xspread, Xbal)
}

#' @title title
#'
#' @description
#' description
#'
#'
#' @param x x
#'
#' @details
#'
#' details
#'
#' @return a vector
#'
#'
#' @author Raphaël Jauslin \email{raphael.jauslin@@unine.ch}
#'
#' @seealso
#' func
#'
#' @examples
#'
#' @export
lcubelandingphase <- function(prob, probflight, Xspread, Xbal) {
    .Call(`_tinyFF_lcubelandingphase`, prob, probflight, Xspread, Xbal)
}

#' @title title
#'
#' @description
#' description
#'
#'
#' @param x x
#'
#' @details
#'
#' details
#'
#' @return a vector
#'
#'
#' @author Raphaël Jauslin \email{raphael.jauslin@@unine.ch}
#'
#' @seealso
#' func
#'
#' @examples
#'
#' @export
cubestratified <- function(prob, Xbal, integerStrata) {
    .Call(`_tinyFF_cubestratified`, prob, Xbal, integerStrata)
}

#' @title title
#'
#' @description
#' description
#'
#'
#' @param x x
#'
#' @details
#'
#' details
#'
#' @return a vector
#'
#'
#' @author Raphaël Jauslin \email{raphael.jauslin@@unine.ch}
#'
#' @seealso
#' func
#'
#' @examples
#'
#' @export
lcubestratified <- function(prob, Xspread, Xbal, integerStrata) {
    .Call(`_tinyFF_lcubestratified`, prob, Xspread, Xbal, integerStrata)
}

#' @title title
#'
#' @description
#' description
#'
#'
#' @param x x
#'
#' @details
#'
#' details
#'
#' @return a vector
#'
#'
#' @author Raphaël Jauslin \email{raphael.jauslin@@unine.ch}
#'
#' @seealso
#' func
#'
#' @examples
#'
#' @export
farma <- function(X, pik, nthreads, EPS = 0.0000001) {
    .Call(`_tinyFF_farma`, X, pik, nthreads, EPS)
}

#' @title title
#'
#' @description
#' description
#'
#'
#' @param x x
#'
#' @details
#'
#' details
#'
#' @return a vector
#'
#'
#' @author Raphaël Jauslin \email{raphael.jauslin@@unine.ch}
#'
#'
#'
#' @export
onestep3 <- function(pik, u, EPS = 0.0000001) {
    invisible(.Call(`_tinyFF_onestep3`, pik, u, EPS))
}

#' @title blab
#'
#' @description skjdfng
#'
#' @return A vector
#'
#' @author Raphaël Jauslin \email{raphael.jauslin@@unine.ch}
#' @export
put01 <- function(done, size, index, pik) {
    invisible(.Call(`_tinyFF_put01`, done, size, index, pik))
}

#' @title title
#'
#' @description
#' description
#'
#'
#' @param x x
#'
#' @details
#'
#' details
#'
#' @return a vector
#'
#'
#' @author Raphaël Jauslin \email{raphael.jauslin@@unine.ch}
#'
#' @seealso
#' func
#'
#' @export
flightphase_arma4 <- function(Xr, pikr, EPS = 0.0000001) {
    .Call(`_tinyFF_flightphase_arma4`, Xr, pikr, EPS)
}

#' @title title
#'
#' @description
#' description
#'
#'
#' @param x x
#'
#' @details
#'
#' details
#'
#' @return a vector
#'
#'
#' @author Raphaël Jauslin \email{raphael.jauslin@@unine.ch}
#'
#' @seealso
#' func
#'
#'
#' @export
test <- function() {
    .Call(`_tinyFF_test`)
}

#' @title title
#'
#' @description
#' description
#'
#'
#' @param x x
#'
#' @details
#'
#' details
#'
#' @return a vector
#'
#'
#' @author Raphaël Jauslin \email{raphael.jauslin@@unine.ch}
#'
#' @seealso
#' func
#'
#'
#' @export
tinyFF <- function(X, pik, EPS = 0.0000001) {
    invisible(.Call(`_tinyFF_tinyFF`, X, pik, EPS))
}

parallelVectorSum <- function(x) {
    .Call(`_tinyFF_parallelVectorSum`, x)
}

#' @title title
#'
#' @description
#' description
#'
#'
#' @param x x
#'
#' @details
#'
#' details
#'
#' @return a vector
#'
#'
#' @author Raphaël Jauslin \email{raphael.jauslin@@unine.ch}
#'
#' @seealso
#' func
#'
#' @examples
#'
#' @export
mainW <- function() {
    .Call(`_tinyFF_mainW`)
}

